### ISSUE TITLE
About FrameLayout Margin/Padding

### ISSUE THREAD

**Issue by WORLD8848** [OneUIProject/oneui-design#8]
Hello!!

I have something to ask about the image below.
The red part is MarginTabLayout. The yellow part is Frame Layout.

In both widgets, the width and height properties are match_parent.

android:layout_width="match_parent"
android:layout_height="match_parent"

But as you can see, can you tell me why the width difference between the two widgets is?

This is an additional question.
Is there a document (e.g. wiki) that summarizes the difference between an existing androidx library and an ONEUI library?

![KakaoTalk_Photo_2022-06-30-23-33-11](https://user-images.githubusercontent.com/65061404/176704207-bd78784e-24fb-4f22-a73c-a85c738dad22.jpeg)

**Comment by salvogiangri** [comment]
We're currently working on our libraries documentation pages, they will soon be added [here](https://oneuiproject.github.io/). MarginTabLayout is a TabLayout ([developer.android.com](https://developer.android.com/reference/com/google/android/material/tabs/TabLayout), [material.io](https://material.io/components/tabs/android)) with additional horizontal padding, we've added this since the stock widget doesn't provide an horizontal padding by default, a minimum of 24.0dp padding is used in Samsung apps that have a Tab UI (Messages, Clock, Gallery, Phone etc.), this view will also adjust the padding depending the screen size to better adapt to tablet screens.

**Comment by WORLD8848** [comment]
Thanks!!
