### ISSUE TITLE
com.google.android.material.button.MaterialButton

### ISSUE THREAD

**Issue by WORLD8848** [OneUIProject/oneui-design#9]
Hello!!!

Can I use <com.google.android.material.button.materialButton> when configuring xml? This is where the error occurs.

Error does not occur when changing to <androidx.appcompat.widget.AppCompatButton> in xml configuration.

**Comment by Yanndroid** [comment]
What's the error? Why don't you use appcompat if it's working?

**Comment by salvogiangri** [comment]
Samsung's Material Components library is somewhat broken since Samsung only uses a few components from it (and messed up all the rest), make sure you only use these widgets:

- AppBarLayout
- BottomNavigationView
- CollapsingToolbarLayout
- Snackbar
- TabLayout

All the rest is not guaranteed to work correctly, so please use only androidx.* widgets and AppCompat/Design styles/themes (avoid MaterialComponents ones).
